version: "3.8"
services:

  sample_postgres:
    image: postgres:12
    ports:
      - "5455:5432"

    environment:
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=sample
      - POSTGRES_DB=sample

  sample_mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: sample
    ports:
      - "3337:3306"