
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'redata_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'redata'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
    redata:time_window_end: null
    redata:time_window_start: null
    redata:anomaly_detection_window_start: null

    redata:schemas:
        - new_testing_dataset
        - redata_sample
        - public
        

    redata:alerting_z_score: 1

    dbt_date:time_zone: 'UTC'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

seeds:
    redata_dbt:
        schema: sample

models:
    redata_dbt:
        anomalies:
            materialized: incremental

        metrics_queries:
            materialized: incremental

        final_metrics:
            materialized: view

        meta:
            materialized: table
    
        last_metrics:
            materialized: view
    